root = "."
tmp_dir = "tmp"

[build]
cmd = "sh ./scripts/dev-build.sh"
bin = "tmp/server"
full_bin = "dlv exec ./tmp/server --headless --listen=:40000 --api-version=2 --accept-multiclient --continue --log"
include_ext = ["go", "templ", "css", "js"]
exclude_dir = ["tmp", "web/node_modules", "vendor"]
exclude_regex = ["_templ\\.go$"]
delay = 1000
stop_on_error = true

[log]
time = false
